---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfcli/cli-base

inputs:
- name: cli
  path: go/src/code.cloudfoundry.org/cli
- name: bosh-lite

params:
  CF_CLI_EXPERIMENTAL: false
  NODES: 16

run:
  path: bash
  args:
  - -c
  - |

    set -e

    source bosh-lite/env
    credhub login --skip-tls-validation
    export CF_INT_PASSWORD=$(credhub get --name '/bosh-lite/cf/cf_admin_password' | bosh interpolate --path /value -)


    export CF_INT_OIDC_USERNAME="admin-oidc"
    export CF_INT_OIDC_PASSWORD=$(credhub get -n /bosh-lite/cf/uaa_oidc_admin_password | bosh interpolate --path /value -)

    set -x
    export CF_INT_API="https://api.${domain}"
    export CF_DIAL_TIMEOUT=15

    export CF_INT_API="https://api.${BOSH_LITE_DOMAIN}"

    export GOPATH=$PWD/go
    export PATH=$GOPATH/bin:$PATH

    cd $GOPATH/src/code.cloudfoundry.org/cli
    make build
    export PATH=$PWD/out:$PATH

    go get -u github.com/onsi/ginkgo/ginkgo

    # TODO uncomment slow integration tests when the rest of the PR builder is working
    ginkgo -r -nodes=$NODES -flakeAttempts=2 -slowSpecThreshold=60 -randomizeAllSpecs integration/shared/isolated # integration/v6/isolated integration/shared/plugin integration/v6/push
    # ginkgo -r -flakeAttempts=2 -slowSpecThreshold=60 -randomizeAllSpecs integration/shared/global integration/v6/global
