---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfcli/cli-base

inputs:
- name: cli
  path: go/src/code.cloudfoundry.org/cli
- name: bosh-lite

outputs:
- name: failure_summary
  path: outputs/failures

params:
  CF_CLI_EXPERIMENTAL: false
  NODES: 8

run:
  path: bash
  args:
  - -c
  - |

    set -e


    source bosh-lite/env
    credhub login --skip-tls-validation
    export CF_INT_PASSWORD=$(credhub get --name '/bosh-lite/cf/cf_admin_password' | bosh interpolate --path /value -)


    export CF_INT_OIDC_USERNAME="admin-oidc"
    export CF_INT_OIDC_PASSWORD=$(credhub get -n /bosh-lite/cf/uaa_oidc_admin_password | bosh interpolate --path /value -)

    export PR_BUILDER_OUTPUT_DIR="$PWD/outputs/failures"

    if [ ! -d $PR_BUILDER_OUTPUT_DIR ]; then
      mkdir -p $PR_BUILDER_OUTPUT_DIR
    fi

    set -x
    export CF_INT_API="https://api.${domain}"
    export CF_DIAL_TIMEOUT=15

    export CF_INT_API="https://api.${BOSH_LITE_DOMAIN}"

    export GOPATH=$PWD/go
    export PATH=$GOPATH/bin:$PATH

    cd $GOPATH/src/code.cloudfoundry.org/cli
    make build
    export PATH=$PWD/out:$PATH

    go get -u github.com/onsi/ginkgo/ginkgo

    set +e
    ginkgo -r -nodes=$NODES -flakeAttempts=2 -slowSpecThreshold=60 -randomizeAllSpecs -keepGoing integration/shared/isolated integration/v6/isolated integration/v6/plugin integration/v6/push
    parallel_failed=$?

    ginkgo -r -flakeAttempts=2 -slowSpecThreshold=60 -randomizeAllSpecs -keepGoing integration/shared/global integration/v6/global
    serial_failed=$?
    set -e

    SUMMARY_FILE="$PR_BUILDER_OUTPUT_DIR/summary.txt"

    cat <<'EOF' > $SUMMARY_FILE
    ### CI Run Summary:
    The following failures were detected in the pipeline:
    ```
    EOF

    cat $PR_BUILDER_OUTPUT_DIR/summary_* | sort >> $SUMMARY_FILE

    echo '```' >> $SUMMARY_FILE

    if [[ $parallel_failed -ne 0 || $serial_failed -ne 0 ]]; then
      exit 1
    fi
