version: 2
updates:
- package-ecosystem: gomod
  directory: '/'
  schedule:
    interval: weekly
    day:      monday
    time:     '01:00'
    timezone: US/Pacific
  open-pull-requests-limit: 2
  commit-message:
    prefix: '[main](go)'
  groups:
    dependencies:
      patterns:
        - '*'
- package-ecosystem: gomod
  directory: '/'
  target-branch: 'v8'
  schedule:
    interval: weekly
    day:      monday
    time:     '01:00'
    timezone: US/Pacific
  open-pull-requests-limit: 2
  commit-message:
    prefix: '[v8](go)'
  groups:
    dependencies:
      patterns:
        - '*'
- package-ecosystem: gomod
  directory: '/'
  target-branch: 'v7'
  schedule:
    interval: weekly
    day:      monday
    time:     '01:00'
    timezone: US/Pacific
  open-pull-requests-limit: 2
  commit-message:
    prefix: '[v7](go)'
  groups:
    dependencies:
      patterns:
        - '*'
- package-ecosystem: 'github-actions'
  directory: '/'
  schedule:
    interval: weekly
    day:      monday
    time:     '01:00'
    timezone: US/Pacific
  open-pull-requests-limit: 2
  commit-message:
    prefix: '[main](gha)'
  groups:
    dependencies:
      patterns:
        - '*'
- package-ecosystem: 'github-actions'
  directory: '/'
  target-branch: 'v8'
  schedule:
    interval: weekly
    day:      monday
    time:     '01:00'
    timezone: US/Pacific
  open-pull-requests-limit: 2
  commit-message:
    prefix: '[v8](gha)'
  groups:
    dependencies:
      patterns:
        - '*'
- package-ecosystem: 'github-actions'
  directory: '/'
  target-branch: 'v7'
  schedule:
    interval: weekly
    day:      monday
    time:     '01:00'
    timezone: US/Pacific
  open-pull-requests-limit: 2
  commit-message:
    prefix: '[v7](gha)'
  groups:
    dependencies:
      patterns:
        - '*'