---
platform: linux

image: docker:///cloudfoundry/cli-vagrant-ci

params:
  LITE_IP_ADDRESS:

inputs:
- name: bosh-lite-lock
- name: etcd-release
- name: garden-runc-release
- name: diego-release
- name: diego-repo
- name: cflinuxfs2-rootfs-release

run:
  path: bash
  args:
  - -c
  - |
    set -eux

    bosh -n target $LITE_IP_ADDRESS
    bosh login admin admin
    bosh upload release cflinuxfs2-rootfs-release/release.tgz --skip-if-exists
    bosh upload release etcd-release/release.tgz --skip-if-exists
    bosh upload release garden-runc-release/release.tgz --skip-if-exists
    bosh upload release diego-release/release.tgz --skip-if-exists

    pushd diego-repo
      bosh download manifest cf-warden cf.yml

      scripts/generate-deployment-manifest \
          -c cf.yml \
          -i manifest-generation/bosh-lite-stubs/iaas-settings.yml \
          -p manifest-generation/bosh-lite-stubs/property-overrides.yml \
          -n manifest-generation/bosh-lite-stubs/instance-count-overrides.yml \
          -v manifest-generation/bosh-lite-stubs/release-versions.yml \
          -s manifest-generation/bosh-lite-stubs/postgres/diego-sql.yml \
          -x \
          > diego.yml
    popd

    bosh deployment diego-repo/diego.yml
    bosh -n deploy

    export DOMAIN=`cat bosh-lite-lock/name`

    curl -L "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github" | tar -zx
    ./cf api "https://api.${DOMAIN}" --skip-ssl-validation
    ./cf auth admin admin
    # This feature flag only affects the diego acceptance tests
    ./cf enable-feature-flag diego_docker

