language: go
go:
  - 1.8
go_import_path: code.cloudfoundry.org/cli
install: true # no-op; install ginkgo from vendor using bin/test
script:  bin/test -nodes=2 -compilers=2
branches:
  only:
  - master
  - travis
addons:
  code_climate:
    repo_token: 5a9ca60422d07f52c50f36aa2c2c101619a19aa64d94fdafb352746b1db8625e
