---
platform: darwin

inputs:
- name: cli
  path: gopath/src/code.cloudfoundry.org/cli
- name: i18n-data

outputs:
- name: osx-compiled

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    cwd=$PWD

    export GOPATH=$PWD/gopath
    export PATH=$GOPATH/bin:$PATH

    go version

    mv i18n-data/i18n_resources.go $GOPATH/src/code.cloudfoundry.org/cli/i18n/resources

    pushd $GOPATH/src/code.cloudfoundry.org/cli
      BUILD_VERSION=$(cat ci/VERSION)
      BUILD_SHA=$(git rev-parse --short HEAD)
      BUILD_DATE=$(date -u +"%Y-%m-%d")

      VERSION_LDFLAGS="-X code.cloudfoundry.org/cli/version.binaryVersion=${BUILD_VERSION} -X code.cloudfoundry.org/cli/version.binarySHA=${BUILD_SHA} -X code.cloudfoundry.org/cli/version.binaryBuildDate=${BUILD_DATE}"

      echo "Building 64-bit Darwin"
      GOARCH=amd64 GOOS=darwin go build -ldflags "-w -s ${VERSION_LDFLAGS}" -o out/cf-cli_osx .

      echo "Creating tarball"
      tar -cvzf $cwd/osx-compiled/cf-cli-osx-binary.tgz -C out .
    popd
