---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfcli/cli-package

inputs:
- name: cross-compiled
- name: osx-compiled

outputs:
- name: compiled

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    cwd=$PWD

    mkdir combined

    pushd cross-compiled
      tar -xvf *.tgz
      rm *.tgz
      mv * $cwd/combined
    popd

    pushd osx-compiled
      tar -xvf *.tgz
      rm *.tgz
      mv * $cwd/combined
    popd

    cd $cwd/combined
    tar -cvzf $cwd/compiled/cf-cli-binaries.tgz *
