---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfcli/cli-package

inputs:
- name: extracted-binaries
- name: packaged
- name: cli

outputs:
- name: archives

run:
  path: bash
  args:
  - -c
  - |
    set -ex
    set -o pipefail

    root=$PWD

    pushd extracted-binaries
      cp $root/cli/ci/license/NOTICE .
      cp $root/cli/ci/license/LICENSE-WITH-3RD-PARTY-LICENSES LICENSE

      tar --transform="flags=r;s|cf-cli_osx|cf|" -czf $root/archives/cf-cli_edge_osx.tgz LICENSE NOTICE cf-cli_osx
      tar --transform="flags=r;s|cf-cli_linux_i686|cf|" -czf $root/archives/cf-cli_edge_linux_i686.tgz LICENSE NOTICE cf-cli_linux_i686
      tar --transform="flags=r;s|cf-cli_linux_x86-64|cf|" -czf $root/archives/cf-cli_edge_linux_x86-64.tgz LICENSE NOTICE cf-cli_linux_x86-64

      awk 'sub("$", "\r")' NOTICE > NOTICE-WINDOWS
      awk 'sub("$", "\r")' LICENSE > LICENSE-WINDOWS
      mv NOTICE{-WINDOWS,}
      mv LICENSE{-WINDOWS,}

      mkdir win32 win64
      mv cf-cli_win32.exe win32/cf.exe
      mv cf-cli_winx64.exe win64/cf.exe
      zip -j $root/archives/cf-cli_edge_win32.zip LICENSE NOTICE win32/cf.exe
      zip -j $root/archives/cf-cli_edge_winx64.zip LICENSE NOTICE win64/cf.exe
    popd

    mv packaged/* archives
