---
platform: linux
image: docker:///cloudfoundry/cli-ci

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:

inputs:
- name: final-cli
  path: cli
- name: cf-cli-binaries
- name: cf-cli-installers
- name: cf-cli-installer-win32
- name: cf-cli-installer-win64

outputs:
- name: cf-cli-osx-tarball

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    root=$PWD

    mkdir archives
    mkdir installers

    pushd cli
      git remote set-url origin https://github.com/cloudfoundry/cli.git
      git fetch --tags
      release_tag=$( git show-ref --tags -d | grep $(git rev-parse HEAD) | cut -d'/' -f3 | egrep 'v[0-9]' | cut -d'v' -f2 )
    popd

    if [ -z "${release_tag}" ]; then
      echo "Expected the commit that triggered this build to be tagged." >&2
      exit 1
    fi

    filename_regex="cf-cli(-installer)?([-_0-9a-z]+)?(\.[a-z]+)?"

    pushd cf-cli-binaries
      tar xvzf cf-cli-binaries.tgz

      for BIN in cf-cli_[lo]*; do # linux, osx
        [[ "${BIN}" =~ $filename_regex ]]
        os_arch="${BASH_REMATCH[2]}"

        cp ${BIN} cf
        tar cvzf $root/archives/cf-cli_${release_tag}${os_arch}.tgz cf
        rm cf
      done

      cp $root/archives/cf-cli_*_osx.tgz ../cf-cli-osx-tarball

      for BIN in cf-cli_win*; do
        [[ "${BIN}" =~ $filename_regex ]]
        os_arch="${BASH_REMATCH[2]}"

        cp ${BIN} cf.exe
        zip $root/archives/cf-cli_${release_tag}${os_arch}.zip cf.exe
        rm cf.exe
      done
    popd

    echo "Uploading final release"

    pushd archives
      for archive in *; do
          aws s3 cp $archive s3://go-cli/releases/v${release_tag}/${archive}
      done
    popd

    pushd cf-cli-installers
      tar xvzf cf-cli-installers.tgz -C $root/installers
    popd

    mv cf-cli-installer-win32/cf-cli-installer_win32.zip installers
    mv cf-cli-installer-win64/cf-cli-installer_winx64.zip installers

    pushd installers
      for installer in *; do
        [[ "${installer}" =~ $filename_regex ]]
        os_arch="${BASH_REMATCH[2]}"
        extension="${BASH_REMATCH[3]}"
        aws s3 cp $installer s3://go-cli/releases/v${release_tag}/cf-cli-installer_${release_tag}${os_arch}${extension}
      done
    popd
