---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfcli/cli-base

inputs:
- name: cli
  path: gopath/src/code.cloudfoundry.org/cli

run:
  path: bash
  args:
  - -c
  - |
    set -e

    export GOPATH=$PWD/gopath
    export PATH=$GOPATH/bin:$PATH

    cd $GOPATH/src/code.cloudfoundry.org/cli

    export LC_ALL="en_US.UTF-8"

    go version

    go get -u github.com/onsi/ginkgo/ginkgo
    ginkgo version

    echo -e "\n Checking that packages have been go formatted..."
    # we don't care about format errors in integration or vendor directories for the units
    unformatted="$(gofmt -l . | grep -v -e  ^vendor -e ^integration)"
    if [[ -z $unformatted ]]
      echo "The following files have not been go formatted:"
      echo $unformatted
      echo "Please run 'make format' and push again."
      exit 1
    fi

    make units-full
