---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfcli/cli-base

inputs:
- name: cli
  path: gopath/src/code.cloudfoundry.org/cli

run:
  path: bash
  args:
  - -c
  - |
    set -e

    export GOPATH=$PWD/gopath
    export PATH=$GOPATH/bin:$PATH

    cd $GOPATH/src/code.cloudfoundry.org/cli

    export LC_ALL="en_US.UTF-8"

    go version

    go get -u github.com/onsi/ginkgo/ginkgo
    ginkgo version

    echo -e "\n Vetting packages for potential issues..."
    go tool vet -all -shadow=true ./api ./actor ./command ./integration ./types ./util ./version
    CF_HOME=$(pwd)/fixtures ginkgo -r -randomizeAllSpecs -randomizeSuites -race -nodes 2 -skipPackage integration,cf/ssh
    CF_HOME=$(pwd)/fixtures ginkgo -r -randomizeAllSpecs -randomizeSuites -race -flakeAttempts 3 cf/ssh
