---
platform: linux

image: docker:///cloudfoundry/cli-vagrant-ci

params:
  LITE_PRIVATE_IP_ADDRESS:
  LITE_HOSTNAME:

inputs:
  - name: cf-release-repo

outputs:
  - name: bosh-lite-cf-manifest

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    export BOSH_LITE_ROOT="$PWD/bosh-lite"

    pushd cf-release-repo
      bosh -n target $LITE_PRIVATE_IP_ADDRESS
      bosh -n login admin admin

      echo "Updating cf-release sub modules"
      ./scripts/update > /dev/null

      echo "Generating bosh lite manifest from cf-release-repo/scripts/generate-bosh-lite-dev-manifest"
      cat > property-overrides.yml << EOF
    properties:
      system_domain: ${LITE_HOSTNAME}
    EOF
      ./scripts/generate-bosh-lite-dev-manifest property-overrides.yml
    popd

    cp cf-release-repo/bosh-lite/deployments/cf.yml bosh-lite-cf-manifest
