---
platform: linux
image: docker:///cloudfoundry/cli-ci

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:

inputs:
- name: cli
- name: cf-cli-binaries
- name: cf-cli-installers
- name: cf-cli-installer-win32
- name: cf-cli-installer-win64

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    root=$PWD

    mkdir archives
    mkdir installers

    filename_regex="cf-cli(-installer)?([-_0-9a-z]+)?(\.[a-z]+)?"

    pushd cf-cli-binaries
      tar xvzf cf-cli-binaries.tgz

      for BIN in cf-cli_[lo]*; do # linux, osx
        [[ "${BIN}" =~ $filename_regex ]]
        os_arch="${BASH_REMATCH[2]}"

        cp ${BIN} cf
        tar cvzf $root/archives/cf-cli_edge${os_arch}.tgz cf
        rm cf
      done

      for BIN in cf-cli_win*; do
        [[ "${BIN}" =~ $filename_regex ]]
        os_arch="${BASH_REMATCH[2]}"

        cp ${BIN} cf.exe
        zip $root/archives/cf-cli_edge${os_arch}.zip cf.exe
        rm cf.exe
      done
    popd

    echo "Uploading edge archives"

    pushd archives
      for archive in *; do
          aws s3 cp $archive s3://go-cli/master/$archive
      done
    popd

    pushd cf-cli-installers
      tar xvzf cf-cli-installers.tgz -C $root/installers
    popd

    mv cf-cli-installer-win32/cf-cli-installer_win32.zip installers
    mv cf-cli-installer-win64/cf-cli-installer_winx64.zip installers

    pushd installers
      for installer in *; do
        [[ "${installer}" =~ $filename_regex ]]
        os_arch="${BASH_REMATCH[2]}"
        extension="${BASH_REMATCH[3]}"

        aws s3 cp $installer s3://go-cli/master/cf-cli-installer_edge${os_arch}${extension}
      done
    popd
