---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfcli/cli-package

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:

inputs:
  - name: cli
  - name: cli-ci
  - name: cli-wiki

outputs:
  - name: cli-wiki-output

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    VERSION=$(cat cli/BUILD_VERSION_V7)
    NOTESFILE="V7-Beta-Release.md"
    TMPFILE="V7-Beta-Release.tmp"

    pushd cli-wiki
      mv "$NOTESFILE" "$TMPFILE"
      ../cli-ci/ci/cli-v7/generate-download-links "$VERSION" > "$NOTESFILE"
      cat "$TMPFILE" >> "$NOTESFILE"
      rm "$TMPFILE"

      git add "$NOTESFILE"

      # create commit in cli-wiki
      if ! [ -z "$(git status --porcelain)" ];
      then
        git config --global user.email "cf-cli-eng@pivotal.io"
        git config --global user.name "Concourse CI"
        git commit -m "Release ${VERSION}"
      else
          echo "no new version to commit"
      fi
    popd
    cp -R cli-wiki cli-wiki-output
