---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfcli/cli-package

params:
  CERT_LOCATION:
  CERT_PASSWORD_LOCATION:

inputs:
- name: certificates
- name: cli
- name: extracted-binaries
- name: winstallers

outputs:
- name: signed-windows-zips

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    VERSION=$(cat cli/ci/VERSION)

    awk 'sub("$", "\r")' cli/ci/license/NOTICE > NOTICE
    awk 'sub("$", "\r")' cli/ci/license/LICENSE-WITH-3RD-PARTY-LICENSES > LICENSE

    mkdir win32 win64
    cp extracted-binaries/cf-cli_win32.exe win32/cf.exe
    cp extracted-binaries/cf-cli_winx64.exe win64/cf.exe
    zip -j signed-windows-zips/cf-cli_${VERSION}_win32.zip win32/cf.exe
    zip -j signed-windows-zips/cf-cli_${VERSION}_winx64.zip win64/cf.exe

    unzip winstallers/cf-cli-installer_winx64.zip

    mkdir signed-64
    osslsigncode sign \
      -pkcs12 certificates/$CERT_LOCATION \
      -pass $(cat certificates/$CERT_PASSWORD_LOCATION) \
      -t http://timestamp.comodoca.com/authenticode \
      -h sha256 \
      -in cf_installer.exe \
      -out signed-64/cf_installer.exe
    rm -f cf_installer.exe

    zip -j signed-windows-zips/cf-cli-installer_${VERSION}_winx64.zip LICENSE NOTICE signed-64/cf_installer.exe

    unzip winstallers/cf-cli-installer_win32.zip

    mkdir signed-32
    osslsigncode sign \
      -pkcs12 certificates/$CERT_LOCATION \
      -pass $(cat certificates/$CERT_PASSWORD_LOCATION) \
      -t http://timestamp.comodoca.com/authenticode \
      -h sha256 \
      -in cf_installer.exe \
      -out signed-32/cf_installer.exe

    zip -j signed-windows-zips/cf-cli-installer_${VERSION}_win32.zip LICENSE NOTICE signed-32/cf_installer.exe
