---
platform: windows

params:
  TARGET_V7:

inputs:
- name: cli
- name: extracted-binaries
- name: winstallers

outputs:
- name: signed-windows-zips

run:
  path: powershell.exe
  args:
  - -command
  - |
    # Print current directory & contents to make debugging easier, for we cannot hijack, but we can `cd`
    Get-ChildItem

    if ($TARGET_V7 -eq "true") {
      Set-Variable Suffix "7"
      type .\cli\BUILD_VERSION_V7 | Set-Variable Version
    } else {
      Set-Variable Suffix ""
      type .\cli\BUILD_VERSION | Set-Variable Version
    }

    # transform the `LICENSE` & `NOTICE` files to include Windows's CRLF https://en.wikipedia.org/wiki/Newline#Representation
    Get-Content .\cli\ci\license\NOTICE | Set-Content NOTICE
    Get-Content .\cli\ci\license\LICENSE-WITH-3RD-PARTY-LICENSES | Set-Content LICENSE

    New-Item -Name win32 -Type "Directory"
    New-Item -Name winx64 -Type "Directory"

    Copy-Item -Path extracted-binaries/cf${Suffix}-cli_win32.exe -Destination win32/cf${Suffix}.exe
    Copy-Item -Path extracted-binaries/cf${Suffix}-cli_winx64.exe -Destination winx64/cf${Suffix}.exe

    Compress-Archive -Path .\LICENSE, .\NOTICE, .\win32\cf${Suffix}.exe `
      -DestinationPath .\signed-windows-zips/cf${Suffix}-cli_${Version}_win32.zip
    Compress-Archive -Path .\LICENSE, .\NOTICE, .\winx64\cf${Suffix}.exe `
      -DestinationPath .\signed-windows-zips/cf${Suffix}-cli_${Version}_winx64.zip

    Expand-Archive -Path .\winstallers\cf${Suffix}-cli-installer_win32.zip `
      -DestinationPath .\cf${Suffix}-cli-installer_win32
    Expand-Archive -Path .\winstallers\cf${Suffix}-cli-installer_winx64.zip `
      -DestinationPath .\cf${Suffix}-cli-installer_winx64

    & 'C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\signtool.exe' `
      sign `
      /tr http://timestamp.sectigo.com `
      /td sha256 `
      /fd sha256 `
      /n "Cloudfoundry.org Foundation, Inc" `
      .\cf${Suffix}-cli-installer_win32\cf_installer.exe

    & 'C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\signtool.exe' `
      sign `
      /tr http://timestamp.sectigo.com `
      /td sha256 `
      /fd sha256 `
      /n "Cloudfoundry.org Foundation, Inc" `
      .\cf${Suffix}-cli-installer_winx64\cf_installer.exe

    Compress-Archive -Path .\LICENSE, .\NOTICE, .\cf${Suffix}-cli-installer_win32\cf_installer.exe `
      -DestinationPath .\signed-windows-zips\cf${Suffix}-cli-installer_${Version}_win32.zip
    Compress-Archive -Path .\LICENSE, .\NOTICE, .\cf${Suffix}-cli-installer_winx64\cf_installer.exe `
      -DestinationPath .\signed-windows-zips\cf${Suffix}-cli-installer_${Version}_winx64.zip
