---
platform: linux

image: docker:///cloudfoundry/cli-ci

params:
  GPG_KEY_LOCATION:

inputs:
- name: certificates
- name: cli
- name: edge-redhat-installer-32
- name: edge-redhat-installer-64

outputs:
- name: signed-redhat-installer

run:
  path: bash
  args:
  - -c
  - |
    set -ex
    cat<<EOF >sign-rpm
    #!/usr/bin/expect -f
    spawn rpmsign --addsign {*}\$argv
    expect -exact "Enter pass phrase: "
    send -- "\r"
    expect eof
    EOF
    chmod 700 sign-rpm

    VERSION=$(cat cli/ci/VERSION)

    cat<< EOF >~/.rpmmacros
    %_gpg_name CF CLI Team <cf-cli-eng@pivotal.io>
    EOF

    mkdir gpg-dir
    export GNUPGHOME=$PWD/gpg-dir
    chmod 700 $GNUPGHOME
    trap "rm -rf $GNUPGHOME" 0

    gpg --import certificates/$GPG_KEY_LOCATION

    ./sign-rpm edge-redhat-installer-32/cf-cli-installer_edge_i686.rpm
    ./sign-rpm edge-redhat-installer-64/cf-cli-installer_edge_x86-64.rpm

    mv edge-redhat-installer-32/cf-cli-installer_edge_i686.rpm signed-redhat-installer/cf-cli-installer_${VERSION}_i686.rpm
    mv edge-redhat-installer-64/cf-cli-installer_edge_x86-64.rpm signed-redhat-installer/cf-cli-installer_${VERSION}_x86-64.rpm
