---
platform: linux

image: docker:///busybox

inputs:
  - name: input

outputs:
  - name: param_to_file_output

params:
  FILE_CONTENTS:
  OUTPUT_PATH:

run:
  path: sh
  args:
  - -c
  - |
    set -eu

    cp -r input/. params_to_file_output

    echo "$FILE_CONTENTS" > params_to_file_output/$OUTPUT_PATH
