---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfcli/cli-package

inputs:
- name: cli
- name: cli-ci
- name: extracted-binaries

outputs:
- name: packaged

run:
  path: bash
  args:
  - -c
  - |
    set -ex
    set -o pipefail

    root=$PWD

    cat<< EOF >~/.rpmmacros
    CF CLI Team <cf-cli-eng@pivotal.io>
    EOF

    VERSION=$(cat cli/BUILD_VERSION)
    RPM_VERSION=$(echo $VERSION | sed 's/-/_/')

    echo "Building 32-bit Debian package"
    (
        SIZE="$(BLOCKSIZE=1000 du $root/extracted-binaries/cf7-cli_linux_i686 | cut -f 1)"

        pushd cli-ci/ci/installers/deb
          mkdir -p cf/usr/bin cf/usr/share/doc/cf-cli/ cf/DEBIAN cf/usr/share/bash-completion/completions

          cp copyright_preamble cf/DEBIAN/copyright
          sed 's/^$/ ./' ../../../LICENSE >> cf/DEBIAN/copyright
          cat copyright_comment_header >> cf/DEBIAN/copyright
          sed 's/^$/ ./' ../../license/3RD-PARTY-LICENSES >> cf/DEBIAN/copyright

          cp cf/DEBIAN/copyright cf/usr/share/doc/cf-cli/copyright

          cp ../../license/NOTICE cf/usr/share/doc/cf-cli
          cp ../../license/LICENSE-WITH-3RD-PARTY-LICENSES cf/usr/share/doc/cf-cli/LICENSE

          cp control_v7.template cf/DEBIAN/control
          echo "Installed-Size: ${SIZE}" >> cf/DEBIAN/control
          echo "Version: ${VERSION}" >> cf/DEBIAN/control
          echo "Architecture: i386" >> cf/DEBIAN/control

          cp ../completion/cf7 cf/usr/share/bash-completion/completions/cf7

          cp $root/extracted-binaries/cf7-cli_linux_i686 cf/usr/bin/cf7

          fakeroot dpkg --build cf cf7-cli-installer_i686.deb
          mv cf7-cli-installer_i686.deb $root/packaged
          rm -rf cf
        popd
    )

    echo "Building 64-bit Debian package"
    (
        SIZE="$(BLOCKSIZE=1000 du $root/extracted-binaries/cf7-cli_linux_x86-64 | cut -f 1)"

        pushd cli-ci/ci/installers/deb
          mkdir -p cf/usr/bin cf/usr/share/doc/cf-cli/ cf/DEBIAN cf/usr/share/bash-completion/completions

          cp copyright_preamble cf/DEBIAN/copyright
          sed 's/^$/ ./' ../../../LICENSE >> cf/DEBIAN/copyright
          cat copyright_comment_header >> cf/DEBIAN/copyright
          sed 's/^$/ ./' ../../license/3RD-PARTY-LICENSES >> cf/DEBIAN/copyright

          cp cf/DEBIAN/copyright cf/usr/share/doc/cf-cli/copyright

          cp ../../license/NOTICE cf/usr/share/doc/cf-cli
          cp ../../license/LICENSE-WITH-3RD-PARTY-LICENSES cf/usr/share/doc/cf-cli/LICENSE

          cp control_v7.template cf/DEBIAN/control
          echo "Installed-Size: ${SIZE}" >> cf/DEBIAN/control
          echo "Version: ${VERSION}" >> cf/DEBIAN/control
          echo "Architecture: amd64" >> cf/DEBIAN/control

          cp ../completion/cf7 cf/usr/share/bash-completion/completions/cf7

          cp $root/extracted-binaries/cf7-cli_linux_x86-64 cf/usr/bin/cf7

          fakeroot dpkg --build cf cf7-cli-installer_x86-64.deb
          mv cf7-cli-installer_x86-64.deb $root/packaged
        popd
    )

    echo "Building 32-bit RedHat package"
    (
      pushd cli-ci/ci/installers/rpm
        cp $root/extracted-binaries/cf7-cli_linux_i686 cf7
        cp ../../license/NOTICE .
        cp ../../license/LICENSE-WITH-3RD-PARTY-LICENSES LICENSE
        cp ../completion/cf7 cf7.bash
        echo "Version: ${RPM_VERSION}" > cf-cli.spec
        cat cf7-cli.spec.template >> cf-cli.spec
        rpmbuild --target i386 --define "_topdir $(pwd)/build" -bb cf-cli.spec
        mv build/RPMS/i386/cf7-cli*.rpm $root/packaged/cf7-cli-installer_i686.rpm
      popd
    )

    echo "Building 64-bit RedHat package"
    (
      pushd cli-ci/ci/installers/rpm
        cp $root/extracted-binaries/cf7-cli_linux_x86-64 cf7
        cp ../../license/NOTICE .
        cp ../../license/LICENSE-WITH-3RD-PARTY-LICENSES LICENSE
        cp ../completion/cf7 cf7.bash
        echo "Version: ${RPM_VERSION}" > cf-cli.spec
        cat cf7-cli.spec.template >> cf-cli.spec
        rpmbuild --target x86_64 --define "_topdir $(pwd)/build" -bb cf-cli.spec
        mv build/RPMS/x86_64/cf7-cli*.rpm $root/packaged/cf7-cli-installer_x86-64.rpm
      popd
    )

    echo "Building OS X installer"
    (
      SIZE="$(BLOCKSIZE=1000 du $root/extracted-binaries/cf7-cli_osx | cut -f 1)"

      pushd cli-ci/ci/installers/osx
        sed -i -e "s/VERSION/${VERSION}/g" Distribution
        sed -i -e "s/SIZE/${SIZE}/g" Distribution
        mkdir -p cf-cli/usr/local/bin cf-cli/usr/local/share/doc/cf7-cli

        cp $root/extracted-binaries/cf7-cli_osx cf-cli/usr/local/bin/cf7
        cp ../../license/NOTICE cf-cli/usr/local/share/doc/cf7-cli
        cp ../../license/LICENSE-WITH-3RD-PARTY-LICENSES cf-cli/usr/local/share/doc/cf7-cli/LICENSE
        chmod -R go-w cf-cli
        pushd cf-cli
          find usr | cpio -o --format=odc | gzip -c > ../Payload
        popd
        ls4mkbom cf-cli | sed 's/1000\/1000/0\/80/' > bom_list
        mkbom -i bom_list Bom
        mv Bom Payload com.cloudfoundry.cli.pkg
        xar -c --compression none -f cf7-cli-installer_osx.pkg com.cloudfoundry.cli.pkg Distribution
        mv cf7-cli-installer_osx.pkg $root/packaged/cf7-cli-installer_osx.pkg
      popd
    )
