---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfcli/cli-package

params:
  CF_API:
  CF_CLIENT_ID:
  CF_CLIENT_SECRET:
  CF_ORGANIZATION:
  CF_SPACE:

inputs:
- name: cli
- name: edge-linux-binary-64

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    tar -zxf edge-linux-binary-64/*.tgz

    LATEST_VERSION=$(cat cli/BUILD_VERSION_V7)

    ./cf7 api "$CF_API"
    ./cf7 auth "$CF_CLIENT_ID" "$CF_CLIENT_SECRET" --client-credentials
    ./cf7 target -o "$CF_ORGANIZATION" -s "$CF_SPACE"
    CURRENT_VERSIONS=$(./cf7 env claw | grep AVAILABLE_VERSIONS | awk '{print $2}')

    if [[ $CURRENT_VERSIONS == *${LATEST_VERSION}* ]]; then
      exit
    fi

    ./cf7 set-env claw AVAILABLE_VERSIONS "${CURRENT_VERSIONS},${LATEST_VERSION}"
    ./cf7 restage claw
