---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfcli/cli-base

inputs:
- name: cf-acceptance-tests
  path: gopath/src/github.com/cloudfoundry/cf-acceptance-tests
- name: cf-cli-binaries
- name: bosh-lite-lock
- name: cats-config

params:
  BACKEND:
  NODES: 2

run:
  path: bash
  args:
  - -c
  - |
    set -eu

    export GOPATH="${PWD}/gopath"
    export PATH="${GOPATH}/bin":${PATH}
    export CF_DIAL_TIMEOUT=15
    export CONFIG=${PWD}/cats-config/integration_config.json

    mkdir -p ${GOPATH}/bin
    pushd cf-cli-binaries
      tar xvf cf-cli-binaries.tgz
      chmod +x cf-cli_linux_x86-64
      ln -s ${PWD}/cf-cli_linux_x86-64 ${GOPATH}/bin/cf
    popd

    export CF_PLUGIN_HOME=${PWD}
    cf install-plugin -f -r CF-Community "network-policy"

    cd "${GOPATH}/src/github.com/cloudfoundry/cf-acceptance-tests"

    # Redact passwords in output
    sed -E 's/(.*(admin_password|existing_user_password).*\:)(.*)/\1 [REDACTED]/' ${CONFIG}

    SKIPS="-skip="
    SKIPS="${SKIPS}transparently proxies both reserved|"

    # Remove trailing |
    SKIPS=$(echo ${SKIPS} | sed -E 's/(.*)(\|)/\1/')

    ./bin/test \
      -flakeAttempts=2 -slowSpecThreshold=180 -randomizeAllSpecs \
      -nodes "${NODES}" \
      "${SKIPS}"
