---
platform: linux
image: docker:///cloudfoundry/cli-ci

inputs:
- name: cf-release-repo
- name: cf-cli-binaries
- name: bosh-lite-lock
- name: cats-config

params:
  BACKEND:
  NODES: 2

run:
  path: bash
  args:
  - -c
  - |
    set -eux

    export GOPATH="${PWD}/cf-release-repo"
    export PATH="${GOPATH}/bin":${PATH}
    export CONFIG=$PWD/cats-config/integration_config.json

    curl ifconfig.co/json

    mkdir -p cf-release-repo/bin
    pushd cf-cli-binaries
      tar xvf cf-cli-binaries.tgz
      chmod +x cf-cli_linux_x86-64
      ln -s $PWD/cf-cli_linux_x86-64 $GOPATH/bin/cf
    popd

    cd "${GOPATH}/src/github.com/cloudfoundry/cf-acceptance-tests"

    go get -u github.com/FiloSottile/gvt
    gvt update github.com/onsi/ginkgo

    # Redact passwords in output
    sed -E 's/(.*(admin_password|existing_user_password).*\:)(.*)/\1 [REDACTED]/' $CONFIG

    SKIPS="-skip="
    [[ "$BACKEND" = "diego" ]] && SKIPS="${SKIPS}NO_DIEGO_SUPPORT|"
    [[ "$BACKEND" = "dea" ]] && SKIPS="${SKIPS}NO_DEA_SUPPORT|"
    [[ "$BACKEND" = "" ]] && SKIPS="${SKIPS}NO_DEA_SUPPORT|NO_DIEGO_SUPPORT|"
    SKIPS="${SKIPS}can delete the key|"
    SKIPS="${SKIPS}dotnet-core|"
    SKIPS="${SKIPS}transparently proxies both reserved|"

    # Remove trailing |
    SKIPS=$(echo $SKIPS | sed -E 's/(.*)(\|)/\1/')

    ./bin/test \
      -flakeAttempts=2 -slowSpecThreshold=120 -randomizeAllSpecs \
      -nodes "${NODES}" \
      "${SKIPS}"
