---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cli-ci

inputs:
- name: cli-ci
- name: cf-cli-binaries
- name: bosh-lite-lock
- name: vars-store

outputs:
- name: cleanup-integration-outputs

run:
  path: bash
  args:
  - -c
  - |
    set -e

    export CF_PASSWORD=$(bosh2 int vars-store/ci/infrastructure/hardknox/deployment-vars.yml --path /uaa_scim_users_admin_password)
    # output password into a temp file for consumption by Windows
    echo $CF_PASSWORD > cleanup-integration-outputs/cf-password

    set -ex

    domain=$(cat bosh-lite-lock/name)
    export CF_API="https://api.${domain}"

    export PATH=$GOPATH/bin:$PATH

    pushd cf-cli-binaries
      tar xvzf cf-cli-binaries.tgz
      chmod +x cf-cli_linux_x86-64
      mv cf-cli_linux_x86-64 $GOPATH/bin/cf
    popd

    cd cli-ci
    bin/cleanup-integration
