---
platform: darwin
image: docker:///cloudfoundry/cli-ci

inputs:
- name: cli
  path: gopath/src/github.com/cloudfoundry/cli

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    export GOPATH=$PWD/gopath
    export PATH=$GOPATH/bin:$PATH

    cd $GOPATH/src/github.com/cloudfoundry/cli

    bin/test -race
